spring:
  application:
    name: shatding-springboot-mybatis
  shardingsphere:
    props:
      sql.show: true
    datasource:
      names: ds2
      # 数据源ds2
      ds2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        # url: jdbc:mysql://localhost:3306/test_order2?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        url: jdbc:mysql://192.168.137.20:3306/dbtest?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        username: root
        password: root